### ISSUE TITLE
Add Google Colab

### ISSUE THREAD

**Issue by franz101** [clovaai/tunit#1]
Love this implementation. For starters it might help some to try it out on Google Colab.

If I have time I try to implement it and open a pull request ;)

**Comment by yunjey** [comment]
@franz101 Thanks! We welcome your future contribution :)

**Comment by sayakpaul** [comment]
Here's one https://colab.research.google.com/drive/1QLINok9nPXOYnf6fTquBT6M_LFqfKsIm?usp=sharing. 

@FriedRonaldo and I will be polishing it more in the coming days.

**Comment by FriedRonaldo** [comment]
Please refer to #2 . The colab written by @sayakpaul can be a good example.
