### ISSUE TITLE
how to visualization t-sne?

### ISSUE THREAD

**Issue by kimtaehyeong** [clovaai/tunit#12]
Hello.
I would like to see the results visualized with T-SNE.
The current dataset is summer2winter.

I want to know how to use it in main.
Thank you.

**Comment by FriedRonaldo** [comment]
Sorry for late. In this version, I commented out the t-SNE visualization in main.py. 

If you want to visualize the map, put a line to call plot_tSNE. (https://github.com/clovaai/tunit/blob/master/main.py#L271)

It might be changed some of the lines in https://github.com/clovaai/tunit/blob/b343337ef30afac0c10d4bac46bb2cdc087e1b36/validation/plot_tsne.py#L28.

**Comment by kimtaehyeong** [comment]
Thank you so much!!
It was very helpful.
