### ISSUE TITLE
the number of the reference image

### ISSUE THREAD

**Issue by ecnuycxie** [clovaai/tunit#13]
the example in paper shows that four reference images are used to extract the average style code. but in code,only one reference image is used.

**Comment by FriedRonaldo** [comment]
The images that you referred are generated with the average of the style codes of all the images in each cluster, not four images.
(The output images are generated with the source image and the average style code of each estimated domain. in the caption of Fig 1.)

We provide the results generated with one reference image in Appendix E. 

This line of code is what you said: https://github.com/clovaai/tunit/blob/master/validation/validation.py#L114

And the image with a single reference is: https://github.com/clovaai/tunit/blob/master/validation/validation.py#L127

Please refer to the captions of the figures.

**Comment by ecnuycxie** [comment]
> The images that you referred are generated with the average of the style codes of all the images in each cluster, not four images.
> (The output images are generated with the source image and the average style code of each estimated domain. in the caption of Fig 1.)
> 
> We provide the results generated with one reference image in Appendix E.
> 
> This line of code is what you said: https://github.com/clovaai/tunit/blob/master/validation/validation.py#L114
> 
> And the image with a single reference is: https://github.com/clovaai/tunit/blob/master/validation/validation.py#L127
> 
> Please refer to the captions of the figures.

thanks for your reply!
it means the style code is extracted from only one images in the trainning process, an i right?

**Comment by FriedRonaldo** [comment]
Yes, you're right.
