### ISSUE TITLE
AdaIN

### ISSUE THREAD

**Issue by ecnuycxie** [clovaai/tunit#14]
hi，FriedRonaldo 
  in your code , the weight and the bias of the 'AdaIN' layer is from the Fully connected
  example : 128-style code  ---FC---->  256  ----FC---->  2*feature_num
  the bias and weight are get from the "2*feature_num"
  can i use the 128-style code to comput mu and sigma, and then comput the 'AdaIN' layer ?
  example : mu = mean(128-style code)         sigma = variance(128-style code)
  what is the difference?

**Comment by FriedRonaldo** [comment]
Well... you can run the code with the modification you referred, but I am not sure that it works well. AdaIN layer is proposed by "Arbitrary Style Transfer in Real-time with Adaptive Instance Normalization". 

The mu/std are not simply mean and standard deviation. Please refer to AdaIN paper.
