### ISSUE TITLE
OOM of training summer2winter 

### ISSUE THREAD

**Issue by jackytu256** [clovaai/tunit#15]
Hi ,

I was trying to train summer2winter and utilize the command as below
```python
python main.py --gpu 0 --dataset summer2winter --output_k 2 --data_path '../data/ob_1001id_paired_images' --p_semi 0 --img_size 128 --batch_size 32
```

I have encountered an issue relating to OOM and you can see the log as below.

```
Traceback (most recent call last):
  File "main.py", line 524, in <module>
    main()
  File "main.py", line 201, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 305, in main_worker
    trainFunc(train_loader, networks, opts, epoch, args, {'logger': logger, 'queue': queue})
  File "/workspace/tunit/train/train_unsupervised.py", line 135, in trainGAN_UNSUP
    d_gp = args.w_gp * compute_grad_gp(d_real_logit, x_ref, is_patch=False)
  File "/workspace/tunit/tools/ops.py", line 16, in compute_grad_gp
    create_graph=True, retain_graph=True, only_inputs=True)[0]
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 158, in grad
    inputs, allow_unused)
RuntimeError: CUDA out of memory. Tried to allocate 180.00 MiB
```

Any suggestion for this ?? Thanks

**Comment by FriedRonaldo** [comment]
Well... In case of OOM, you can try the experiment with GPU having larger memory or reduce the size of the networks.

Please refer to issue #9

**Comment by jackytu256** [comment]
The gpu I have is 2080ti which contains 11g memory so I reckon memory capacity is not a main issue for this??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FriedRonaldo** [comment]
Unfortunately, memory capacity is the main issue. I also have 2080ti but I can not run the code on a single 2080ti. 

This project is mainly done with V100 and P40 (2xP40).

With batch_size=32 and img_size=128, you might need more than 24GB.

**Comment by jackytu256** [comment]
Thanks for your suggestions @FriedRonaldo

The model is initialized with roughly usage of 6g memory and can be trained till 65 epochs to occur OOM. Do I need to provide more info for you to figure out what the issue is ? or I just follow the steps with issue #9.

Thanks for the quick reply!


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FriedRonaldo** [comment]
Actually, it is totally from the memory capacity. I already tried running the code with a single 2080ti that is the same model you have.

More specifically, that behavior is intended. Untill 65 epoch, the code trains the guiding network only for the stability. 

After the point, GANs training starts and the guiding network and GANs are trained with the overall objectives.

So, only small memory is required before the entire training so that you can run the code while 65 epochs but cannot after 65 epoch.

Please follow issue #9. 

Thanks.

**Comment by jackytu256** [comment]
Thanks a lot !! Fried

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
