### ISSUE TITLE
Seek the AnimalFaces Dataset

### ISSUE THREAD

**Issue by zhwhong** [clovaai/tunit#17]
Hello!
I'm interested in the experiment of AnimalFaces Dataset, but I didn't find a pure AnimalFaces in public work like FUNIT, the cost of dowmloading the original ImageNet is too large for me, so I wander if you have uploaded the AnimalFaces Dataset (not afhq) to some online network location? I believe it will be very helpful if they have already been uploaded.
Best!

**Comment by FriedRonaldo** [comment]
Unfortunately, the AnimalFaces dataset is not our contribution, so we can not provide the dataset. Providing the dataset might cause a copyright problem. 

I am sorry that I can not help you.

I think that you already checked the issues of FUNIT repository, however, I recommend you to request the dataset from the authors of FUNIT.

Thanks.

**Comment by zhwhong** [comment]
Ok, I got it. Thanks a lot.
