### ISSUE TITLE
FFHQ: IndexError list index out of range

### ISSUE THREAD

**Issue by nihirv** [clovaai/tunit#19]
Hey, I'm trying to get the tunit algorithm running with FFHQ (thumbnails) which are size 128x128. Just for context (although I don't think this is relevant) I had downloaded it from the Drive link (found [here](https://github.com/NVlabs/ffhq-dataset)). The way that this code had been set up for FFHQ wasn't quite correct as it didn't take into account the folder structure so I modified the relvant sections everything from `tot_targets` on line 327 in datasetgetter.py to:
```python
train_dataset = dataset
all = list(range(70000))
val_idx = random.sample(all, 7000)
train_idx = list(filter(lambda x: x not in val_idx, all))[:-24]  # make sure train_idx is evenly divisible by batch_size of 32
``` 

Now, when I go to train, the places errors get thrown are very confusingly not the same. Occasionally I will get a stack-trace pointing to `for _, (data, _) in enumerate(train_loader):` at line 142 (initialize_queue) in ops.py. More commonly though, I will get a stack-trace pointing to `imgs, _ = next(train_it)` at line 62 (trainGAN_UNSUP) in train_unsupervised.py:
```python
Traceback (most recent call last):
  File "main.py", line 527, in <module>
    main()
  File "main.py", line 201, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 305, in main_worker
    trainFunc(train_loader, networks, opts, epoch, args, {'logger': logger, 'queue': queue})
  File "/data/nv419/machine_drive/tunit/train/train_unsupervised.py", line 62, in trainGAN_UNSUP
    imgs, _ = next(train_it)
  File "/data/nv419/anaconda3/envs/tunit/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/data/nv419/anaconda3/envs/tunit/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/data/nv419/anaconda3/envs/tunit/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/data/nv419/anaconda3/envs/tunit/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/nv419/anaconda3/envs/tunit/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/nv419/anaconda3/envs/tunit/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/nv419/anaconda3/envs/tunit/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 256, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/data/nv419/anaconda3/envs/tunit/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 137, in __getitem__
    path, target = self.samples[index]
IndexError: list index out of range
```

Normally this error gets thrown at the 0th iteration. However,  I've seen the tqdm bar (at times) move up to 4 iterations before having the error thrown 🤷‍♂️:
![image](https://user-images.githubusercontent.com/31130127/103315525-bf5d4580-4a1d-11eb-9e96-3c5e913a1357.png)

Been at this for hours now but the code isn't trivial to understand so I'm hoping one of the maintainers has some intuition behind this. Using Pytorch v1.2.0 on an Ubuntu machine. Error is there whether I'm using multiple GPUs or not

**Comment by nihirv** [comment]
@FriedRonaldo Any thoughts?

**Comment by FriedRonaldo** [comment]
I just merged all the subfolders into a single folder. It is easy to implement (just read and write).

That is why I used Imagefolder class to load them.

I cannot understand that I did not consider the folder structure. FFHQ does not have any labels, so there is no need to consider that kind of structure. Just read images irrelevant to labels.

Merge and load. That's all. To debug it, print "index" and the length of "self.samples" by modifying the imageFolder class temporarily.

Unfortunately, I have no time enough to analyze the code that I did not write. I am sorry for that.

Place the dataset : 
~dataroot/ffhq/images/00001.jpg....70000.jpg
(dataroot depends on your file structure)
Then, it works well without any modification.

**Comment by nihirv** [comment]
Thanks - I'm unsure why this works but it does (although I seem to be getting an OOM error at epoch 11). Your code is well documented for research code so I was confused regarding what should be done with FFHQ because there wasn't a comment in the README saying that we'd need to modify the folder structure.

Anyway I'll tinker around and see if I can figure out why my code didn't work and to try sort out the OOM issue. Thanks for your help 👌. Feel free to close the issue (unless you have comments on OOM)

**Comment by FriedRonaldo** [comment]
Sorry for the confusion with the dataset. The reason that the file structure works is that I used ImageFolder class to generate a dataset generator.

Related to the OOM issue, please refer to #11 and #15 (especially, EDIT in the first reply of 11)
These issues might be helpful.
