### ISSUE TITLE
Training on non-square images

### ISSUE THREAD

**Issue by ffabi** [clovaai/tunit#20]
Hi, 

is it possible to train on images with a different vertical and horizontal resolution?

Is it possible to train on images which are not the power of 2? 

Thanks, Fabian

**Comment by FriedRonaldo** [comment]
Hi.

**is it possible to train on images with a different vertical and horizontal resolution?**
* Well... I did not try that kind of experiment. However, it might work if you change the last layer of the discriminator (it assumes that the size of the last feature map is B, C, 4, 4).

**Is it possible to train on images which are not the power of 2?**
* It might be okay... However, I am not sure.

Best,
Kyungjune Baek
