### ISSUE TITLE
About Food-10 dataset settings

### ISSUE THREAD

**Issue by ZYJ-JMF** [clovaai/tunit#25]
HI,sorry to bother you.
But I have some questions when I try to reproduce the quantitive result in Food -10 dataset.
I add the food-10 dataset in code and use the same settings as 'animal faces' dataset.

When I run the code  of 'animal faces'.I can get the best mFID：49.1 when paper gave the mFID as 47.7.
But when I run the code  of 'food-10'.I can get the best mFID：69.50 when paper gave the mFID as 52.2
I use pytorch 1.9.0. 
I think the difference mFID between animal faces is reasonable.But the 'food-10' is strange.
So I am wondering that if you use different settings in 'food-10' dataset?
Thanks

**Comment by FriedRonaldo** [comment]
I think the version of pytorch might not be a problem.

The augmentation policy is the main difference [(code)](https://github.com/clovaai/tunit/blob/food_added/datasets/datasetgetter.py#L35).

Please check if you use this strong augmentation. 

I ran the code twice and got 52.07 and 52.22 (mean of five best scores in the training).
If you need the pre-trained model, I will provide the ckpt file.

Thanks.

**Comment by FriedRonaldo** [comment]
mistakenly closed sorry.

**Comment by FriedRonaldo** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/bkjbk/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/bkjbk/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



step | value | value
-- | -- | --
67 | 224.3132 | 265.8067
68 | 183.3408 | 240.3664
69 | 185.8064 | 193.2972
70 | 171.6848 | 201.0911
71 | 157.8202 | 173.9646
72 | 166.732 | 174.2087
73 | 159.1015 | 184.9025
74 | 148.4935 | 166.3003
75 | 142.8301 | 184.0244
76 | 149.8664 | 153.267
77 | 145.9465 | 181.8953
78 | 186.0997 | 153.2928
79 | 113.7879 | 139.5919
80 | 132.4512 | 143.1434
81 | 143.7819 | 126.8753
82 | 120.6133 | 168.8693
83 | 131.4829 | 151.5914
84 | 111.7385 | 124.3411
85 | 94.16042 | 101.6356
86 | 119.9972 | 106.8126
87 | 109.1241 | 136.9823
88 | 91.28201 | 115.7551
89 | 104.3784 | 111.9891
90 | 97.63063 | 87.77061
91 | 96.77477 | 103.6436
92 | 92.54055 | 104.549
93 | 78.86362 | 87.85582
94 | 140.7672 | 124.0697
95 | 73.20503 | 88.75333
96 | 87.90899 | 74.06078
97 | 70.18404 | 71.66871
98 | 102.4793 | 101.5792
99 | 95.20749 | 75.69092
100 | 71.93134 | 77.59294
101 | 64.07443 | 75.84999
102 | 85.89972 | 65.5535
103 | 91.01683 | 64.75001
104 | 68.30079 | 96.77974
105 | 71.21319 | 81.34402
106 | 75.03713 | 87.4193
107 | 81.38832 | 89.21696
108 | 74.41141 | 66.78207
109 | 61.45426 | 72.52018
110 | 63.03598 | 66.12524
111 | 74.62017 | 66.09839
112 | 60.63811 | 66.60176
113 | 65.6084 | 60.99644
114 | 68.45677 | 76.50219
115 | 75.18992 | 83.49175
116 | 61.53345 | 73.73632
117 | 62.23727 | 70.42416
118 | 55.19578 | 78.62976
119 | 59.66957 | 63.47365
120 | 74.83722 | 66.9161
121 | 61.74528 | 60.41241
122 | 72.84798 | 76.65596
123 | 61.83128 | 60.48172
124 | 61.22198 | 71.89203
125 | 62.68183 | 57.59319
126 | 63.93945 | 56.39276
127 | 55.39524 | 60.70088
128 | 58.53039 | 58.34474
129 | 58.52422 | 79.21448
130 | 60.41211 | 66.56722
131 | 52.80946 | 62.45663
132 | 59.22621 | 53.27441
133 | 62.4398 | 55.38682
134 | 58.01872 | 53.46791
135 | 57.18331 | 67.6344
136 | 54.37372 | 54.76342
137 | 75.67352 | 55.72251
138 | 60.52889 | 58.11519
139 | 52.18312 | 65.40696
140 | 56.64669 | 54.52291
141 | 65.44593 | 52.72928
142 | 55.26692 | 53.97153
143 | 61.64132 | 55.57161
144 | 61.65961 | 77.42241
145 | 55.26279 | 60.34202
146 | 53.98606 | 58.75065
147 | 53.95395 | 66.62949
148 | 60.9488 | 53.9631
149 | 55.74121 | 64.94775
150 | 54.50622 | 66.4997
151 | 74.54728 | 51.75571
152 | 51.36107 | 52.15461
153 | 55.47255 | 62.66975
154 | 60.73539 | 53.15031
155 | 53.12493 | 57.9297
156 | 54.48961 | 61.17676
157 | 61.88296 | 54.57003
158 | 51.96513 | 68.78396
159 | 55.80614 | 54.91952
160 | 56.38723 | 52.91188
161 | 55.15436 | 58.02267
162 | 54.28942 | 50.80658
163 | 57.24655 | 55.90813
164 | 55.37147 | 56.16179
165 | 60.68079 | 58.29176
166 | 52.79157 | 67.65731
167 | 54.85587 | 58.23893
168 | 57.8695 |  



</body>

</html>

These are the mFID scores during training. Each column shows a result of a single running.

**Comment by ZYJ-JMF** [comment]
Thanks for your response~
I think I ignore the strong augmentation~
But I can not find the details about the 'Augment()'.Could  you explain it?
Thanks
And I will record the fid in every steps and compare with your scores~

**Comment by FriedRonaldo** [comment]
@ZYJ-JMF 
I am sorry for the inconvenience. I just concatenated two projects. I missed the file. 

EDIT

Please write this [code](https://github.com/evilc3/SCAN/blob/67adef402c90e4507aa0f45b30071428516d6644/data/augment.py) as "randaug.py" and put inside "datasets" folder. And set n=4 in init function of Augment().

**Comment by ZYJ-JMF** [comment]
Got it~
Thanks.



At 2021-10-13 16:14:30, "FriedRonaldo" ***@***.***> wrote:

Because of the license issue, I will fix it please wait a moment.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
