### ISSUE TITLE
Average style vectors?

### ISSUE THREAD

**Issue by ammar-deep** [clovaai/tunit#26]
In Figure 17 (a), style vectors are averaged for domain translation. I tried to find this in your code but haven't found yet. Could you please let me know the code where you have done this? or how to generate averaged style vector translated images?

**Comment by FriedRonaldo** [comment]
Please refer to line 110 in validation.py [(Link)](https://github.com/clovaai/tunit/blob/master/validation/validation.py#L110)
The code below calculates the style vector of each image of each cluster, then gets the average vector by using "mean" operation.
```
                for i in range(len(cluster_grid)):
                    s_tmp = C_EMA.moco(cluster_grid[i])
                    s_avg = torch.mean(s_tmp, 0, keepdim=True)
                    s_avg = s_avg.repeat((grid_row, 1, 1, 1))
```

**Comment by ammar-deep** [comment]
Thank you.
