### ISSUE TITLE
pretarined food10 weights

### ISSUE THREAD

**Issue by sunwoo76** [clovaai/tunit#31]
Hello.

Do you have any plan to upload other pre-trained weights of another setting that were used in your paper?

Unless can you upload only trained food10 weights of which the number of domain is 10.

Thanks.

**Comment by FriedRonaldo** [comment]
Hi,

1) Which setting do you mean? Do you mean the models with different K's?

2) I will find them and check if it is available. If it is okay, I will upload them and notice them as soon as possible.

**Comment by sunwoo76** [comment]
Thank you for replying.

I mean the setting of which "K" is 10 with food-10 dataset.

**Comment by FriedRonaldo** [comment]
Well, I got it. 

Firstly, I intended:

Do you have any plan to upload other pre-trained weights of another setting that were used in your paper? 
- Do you mean the models with different K's on AnimalFaces and Food? Or the semi-supervised setting on Animal149 and Food101?

Unless can you upload only trained food10 weights of which the number of domain is 10.
- I will find them and check if it is available. If it is okay, I will upload them and notice them as soon as possible.

Please check if I understand your comment correctly with above comments.

---

If the weight that you only need is the model with K=10 on Food-10 under unsupervised manner, I will find it and upload on the drive soon (hopefully later today)

**Comment by sunwoo76** [comment]
Yes, I only need the model with K=10 on Food-10 under an unsupervised manner now.

Thank you.

**Comment by FriedRonaldo** [comment]
@sunwoo76 I uploaded the file at "pretrain_upload/Food10_0_00". For the fast upload, I've not checked if it is correct by running it. (if you have any trouble, please reopen this issue.) But it should be the checkpoint file that you want if my record about the files is correct.
