### ISSUE TITLE
D and G losses are 0s

### ISSUE THREAD

**Issue by sizhky** [clovaai/tunit#4]
Hi so far i started training using 
```python
python main.py --dataset afhq_wild --output_k 10 --data_path '/home/yyr/data/' --p_semi 0.0 --img_size 128 --batch_size 16
```

But even at 10th epoch D and G have 0 losses. Is this expected or abnormal?
`Epoch: [10/200] [500/1000] MODE[ONLYCLS] Avg Loss: D[0.00] G[0.00] C[2.61]`

I am not seeing any items in the corresponding results folder for the run even after 9 epochs.... At what point does it give results?

**Comment by sizhky** [comment]
I forgot to revert some debugging code that I wrote

**Comment by FriedRonaldo** [comment]
This is expected. Until 65 epochs
