### ISSUE TITLE
How to use custom dataset

### ISSUE THREAD

**Issue by Iarkii** [clovaai/tunit#5]
Hi~  Is it possible to use custom datasets for training? Thanks!

**Comment by Meulen92** [comment]
Also interested to know. Many thanks in advance.

**Comment by FriedRonaldo** [comment]
Hi, Thanks for your interest. Basically, "ImageFolderRemap" works the same as "ImageFolder", but it contains the remapping of labels. 

To use your own dataset, please follow the steps below.

1. First, place the dataset as below (or README)
```
Project
|--- tunit
|          |--- main.py
|          |--- train
|                 |--- train_unsupervised.py
|                 |--- ...
|
|--- data
       |--- your_data
             |--- train
                     |--- wild
                     |--- cat
                     |--- dog
             |--- test
                     |--- wild
                     |--- cat
                     |--- dog
or

       |--- your_data
             |--- n02085620
             |--- n02085782
             |--- ...
```

Assume that you choose to use the latter one (your_data - class folders)
2. Replace wild/cat/dog to your label. If you do not have any label, just use any name (ex. class1).
```
|--- data
       |--- your_data
              |--- class1
```

3. Add your own dataset getter as https://github.com/clovaai/tunit/blob/master/datasets/datasetgetter.py#L114
4. Add the name of the dataset to choices in https://github.com/clovaai/tunit/blob/master/main.py#L42
5. Add classes to use for your dataset as https://github.com/clovaai/tunit/blob/master/main.py#L226 (if you do not have labels, just [0,] as ffhq and lsun_car.)
6. If you do not have any labels, add your dataset name to https://github.com/clovaai/tunit/blob/master/main.py#L310

Update
7. As 6. add the name to https://github.com/clovaai/tunit/blob/master/main.py#L325

---
After writing the steps, I recognize the need for refactoring for the additional dataset. I will update the codes to ease the steps.

**Comment by Iarkii** [comment]
Thanks so much!

**Comment by Meulen92** [comment]
Much appreciated, @FriedRonaldo . Thank you!
