### ISSUE TITLE
'fid_ema' referenced before assignment Error!

### ISSUE THREAD

**Issue by chokyungjin** [clovaai/tunit#6]
Hi. I'm so glad to see your model! But I have some issue. 
I'm going to learn from custom data, But I met

Traceback (most recent call last):
  File "main.py", line 524, in <module>
    main()
  File "main.py", line 201, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 327, in main_worker
    add_logs(args, logger, 'STATEMA/G_EMA{}/FID'.format(idx_fid), fid_ema[idx_fi      d], epoch + 1)
UnboundLocalError: local variable 'fid_ema' referenced before assignment

this issue. 
How can I Solve this Problem? Thanks!

**Comment by FriedRonaldo** [comment]
Thanks for letting me know the error.
It seems that you add the name of your dataset to 
https://github.com/clovaai/tunit/blob/master/main.py#L310
But not to https://github.com/clovaai/tunit/blob/master/main.py#L325

If you do not need to calculate FID, you should add the name of the dataset to both lines.
I missed this line in #5. I will update the comment.
