### ISSUE TITLE
training on own dataset

### ISSUE THREAD

**Issue by anish9** [clovaai/tunit#7]
how can we train in on custom domains??? when i try i am getting error
`Traceback (most recent call last):
  File "main.py", line 524, in <module>
    main()
  File "main.py", line 201, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 257, in main_worker
    train_loader, val_loader, train_sampler = get_loader(args, {'train': train_dataset, 'val': val_dataset})
  File "main.py", line 478, in get_loader
    pin_memory=True, sampler=train_sampler, drop_last=False)
  File "/home/mia/anish/experiments/tunit/tunitenv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/mia/anish/experiments/tunit/tunitenv/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
`

**Comment by FriedRonaldo** [comment]
Hi, the error seems that the number of data is zero. 

The possible cause is the wrong directory of a dataset.

Please check the directory of your dataset.

You can check the length of the dataset instance or print the elements of "glob".

**Comment by anish9** [comment]
@FriedRonaldo  I have arranged datapath as per your guidelines on the readme and there are images in

**Comment by FriedRonaldo** [comment]
Edit
Issue #5 is a related issue. If you did not notice this issue, please check #5 

---
Ok, I see. Would you check the length of the dataset instance by adding a line (print(train_dataset) and print(train_dataset['TRAIN'])) at https://github.com/clovaai/tunit/blob/master/main.py#L256?

I need more information to solve the issue.

**Comment by anish9** [comment]
@FriedRonaldo  I have printed
` {'TRAIN': <torch.utils.data.dataset.Subset object at 0x7f6ff4289550>, 'FULL': Dataset ImageFolder
    Number of datapoints: 2100
    Root location: data/lsun-car`

**Comment by FriedRonaldo** [comment]
@anish9 Thanks. Would you print the length of train_dataset['TRAIN'] by print(train_dataset['TRAIN']) also? It might be zero.

If so, I think you use the small subset of lsun-car (or just keep the directory as lsun-car and replace the inner items only;images), then, the number of the validation dataset is set to 7000. However, the total number of your dataset seems to be 2100. 

In this case, you can solve the problem by

1. Change the number of validation dataset from 7000 to a number smaller than 2100. (Change -7000 to a number{ex.-500} in https://github.com/clovaai/tunit/blob/master/datasets/datasetgetter.py#L317)

or

2. Make another if-else branch similar to the code from https://github.com/clovaai/tunit/blob/master/datasets/datasetgetter.py#L316 to L343. 
If you decide to follow the second one, please refer to #5

**Comment by anish9** [comment]
@FriedRonaldo  Thanks for your kind response,  I have manged to start the training but i am getting 
`Epoch: [2/200] [100/500] MODE[SUP] Avg Loss: D[0.00] G[0.00] C[2.61]`
it shows D and G have 0.00 as loss, can i get a view on how to interpret this??

Thanks again!!!

**Comment by FriedRonaldo** [comment]
@anish9 Good to hear you solved the issue.

It is intended. You can change the behavior by modifying the line in https://github.com/clovaai/tunit/blob/master/main.py#L127.

Please refer to #4 . The code trains the guiding network only during 65 epochs.

---
Edit
fix the typo
by modify -> by modifying

**Comment by anish9** [comment]
@FriedRonaldo  Thanks for updating
