### ISSUE TITLE
issue when loading a checkpoint file

### ISSUE THREAD

**Issue by anish9** [clovaai/tunit#8]
Hi, I used the following code load the checkpoint:

G = DataParallel(Generator(img_size=512,sty_dim=128))
C = DataParallel(GuidingNet(128))
load_file = "./ologs/GAN_20200630-174700/model_42.ckpt"
checkpoint = torch.load(load_file, map_location="cuda:0")
G.load_state_dict(checkpoint["G_EMA_state_dict"]) #G_EMA_state_dict
C.load_state_dict(checkpoint['C_EMA_state_dict'])
G.to(device="cuda")
C.to(device="cuda")
G.eval()
C.eval()
c_src = G.cnt_encoder(x_src)
s_ref = C.moco(x_ref)
x_res = G.decode(c_src, s_ref)

i am getting the following error:
`
AttributeError: 'DataParallel' object has no attribute 'cnt_encoder'`

since i don't have great experience with pytorch i am not able to figure how to actually load without dataparallel. let me know how i can solve and run the inference part,
Thanks

**Comment by FriedRonaldo** [comment]
In the code of this repos., I provide the load function for the case when you train with dataparallel and test withouy dataparallel in https://github.com/clovaai/tunit/blob/master/main.py#L404.

The core functionality of the method is to remove "module" from the checkpoint file if it exists.

In this case, you can solve the problem via
1. Using the code in L404 to load and remove DataParallel in your loading code.

or

2. Replacing G.cnt_encoder.... to G.module.cnt_encoder. It means that you should add "module" after G and C to call the member variable or method in the model instance.

I think the second one might be easier to use. However, if you want to run the code w/o datapatallel, please follow the first solution or remove "module" in the ckpt manually by using the partial code of L404.

--
Edit
You can check this post; https://discuss.pytorch.org/t/how-to-reach-model-attributes-wrapped-by-nn-dataparallel/1373

**Comment by anish9** [comment]
@FriedRonaldo  thanks for the support!!!
