### ISSUE TITLE
Training on smaller GPU

### ISSUE THREAD

**Issue by Meulen92** [clovaai/tunit#9]
Hi @FriedRonaldo ,

First of all, thank you for the awesome work.

My question is, do you have any pointers for training on a GPU with less RAM? Like my 2070 8GB?

For example, I keep getting CUDA out of memory messages when training with two classes/labels. Even when decreasing batch_size and val_batch significantly.

Many thanks in advance.

**Comment by FriedRonaldo** [comment]
Thanks for your interest! I know that it is painful to train the models with the small size of memory.

Well, you might try decreasing the image size and the network size. You can adjust the image size by providing an argument, --img_size 64.

For network size, reducing the number of filters is an option. You can change the network size by changing these lines:
For discriminator and generator:
https://github.com/clovaai/tunit/blob/master/models/discriminator.py#L27
https://github.com/clovaai/tunit/blob/master/models/generator.py#L25
nf=64 to nf=32 or nf=16

For guiding network:
https://github.com/clovaai/tunit/blob/master/models/guidingNet.py#L15
Reduce the size of channels from 64, 128, 256, 512 to 32(or 16), 64 ...

And if you do not need to calculate FID, then you can reduce the required memory by removing the inceptionV3 network from the code.

Or, training with quantization can be a possible option. I am not sure that it works for TUNIT, however, it can significantly reduce the memory size.
This repository might help you: https://github.com/clovaai/StatAssist-GradBoost . The repo. provides the codes to train a model with quantization for image-to-image translation models; CycleGAN and pix2pix.

I hope that these pointers would help you.

**Comment by Meulen92** [comment]
Very helpful tips! Awesome. Thanks again for the quick reply.
